# .github/workflows/nodejs-ci.yml
    name: Node.js CI/CD Pipeline

    on:
      push:
        branches:
          - main 
      pull_request:
        branches:
          - main 

    jobs:
      build-test-and-package:
        runs-on: ubuntu-latest 

        steps:
        - name: Checkout Repository 
          uses: actions/checkout@v4
         

        - name: Set up Node.js Environment 
          uses: actions/setup-node@v4
          with:
            node-version: '18' 
            cache: 'npm'

        - name: Install Dependencies 
          run: npm ci 

        - name: Compile Code (Conceptual for Node.js) 
        
          run: echo "Node.js es interpretado, la 'compilación' es conceptual o para transpilación/linting."
    

        - name: Run Unit Tests 
          run: npm test 

        - name: Build Application / Package (Conceptual)
      
          run: echo "Realizando un 'build' conceptual para la aplicación Node.js."
         
    
